Revert "qcacld-3.0: Fix compile error of mdie"
Fix compilation with Snapdragon Clang 17

error: argument 'mdie' of type 'uint8_t[]' (aka 'unsigned char[]') with mismatched bound [-Werror,-Warray-parameter]
                   uint8_t mdie[])

This reverts commit eab989ad6c93eae3ad0685d92cf91f63aa76af79.