sched/fair: Fix error with missing argument
fixing this error:
../kernel/sched/fair.c:12312:53: error: too few arguments to function call, expected 2, have 1
 12312 |         bool prefer_spread = prefer_spread_on_idle(this_cpu);
       |                              ~~~~~~~~~~~~~~~~~~~~~         ^
../kernel/sched/walt.h:474:20: note: 'prefer_spread_on_idle' declared here
  474 | static inline bool prefer_spread_on_idle(int cpu, bool new_ilb)
      |                    ^                     ~~~~~~~~~~~~~~~~~~~~~
1 error generated.