crypto: msm: Fix incorrect boolean logic
Fix the following warning from gcc 7.4.1 with -Werror enabled:

 drivers/crypto/msm/qce50.c:4668:28: error: ‘~’ on a boolean expression
  [-Werror=bool-operation]
  pce_dev->cadence_flag = ~pce_dev->cadence_flag;

 drivers/crypto/msm/qce50.c:4668:28: note: did you mean to use logical not?.

Fixes: 377c69bf3e72 ("crypto: msm: Add QTI crypto drivers")
Change-Id: Ic0dedbad73c49d059d68d9412009b74583d33154
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>